-- create database customer_behavior;
use customer_behavior;
select * from shopping_table limit 20;
Alter Table shopping_table CHANGE `Purchase Amount (USD)` Purchase_Amount INT; 

-- What is the total revenue generated by male vs. female customers?
Select gender,sum(Purchase_Amount) as revenue
from shopping_table
group by gender;

select `Customer ID`,Purchase_Amount
from shopping_table
where `Discount Applied`='Yes' and Purchase_Amount>= (select AVG(Purchase_Amount) from shopping_table);

select `Item Purchased`,ROUND(AVG(`Review Rating`),2) as "Average Product Rating"
from shopping_table
GROUP BY `Item Purchased`
ORDER BY AVG(`Review Rating`) DESC limit 5  ;


Select `Shipping Type`,ROUND(avg(Purchase_Amount),2)
from shopping_table
where `Shipping Type`in ("Express","Standard")
group by `Shipping Type`;

select `Subscription Status`,
COUNT(`Customer ID`) as total_customer,
ROUND(SUM(Purchase_Amount),2) as total_revenue,
ROUND(AVG(Purchase_Amount),2) as avg_spend
from  shopping_table
group by `Subscription Status`
order by total_revenue,avg_spend;


select `Item Purchased`,
ROUND(100*SUM(CASE WHEN `Discount Applied`='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from shopping_table
group by `Item Purchased`
order by discount_rate desc
limit 5;


with customer_type as (
select `Customer ID`,`Previous Purchases`,
CASE
    WHEN `Previous Purchases`=1 THEN "New"
	WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN "Returning"
	ELSE "Loyal"
    END AS customer_segment
from shopping_table
)
    
select customer_segment,count(*) as "Number of customers"
from customer_type
group by customer_segment;

with item_counts as (
select `Category`,`Item Purchased`,
COUNT(`Customer ID`) as total_counts,
ROW_NUMBER() OVER(partition by category order by count(`Customer ID`) DESC) as item_rank
from shopping_table
group by `Category`,`Item Purchased`
)

select item_rank,`Category`,`Item Purchased`,total_counts
from item_counts
where item_rank<=3;

select `Subscription Status`,
count(`Customer ID`) as repeat_buyers
from shopping_table
where `Previous Purchases`>5
group by  `Subscription Status`;


select age_group,sum(`Purchase_Amount`) as revenue
from shopping_table
group by age_group
order by revenue desc ;



